import prisma from "../config/prisma.js"
import { Prisma } from "@prisma/client";

export const userRepository={
    createUser:(data:Prisma.UserCreateInput)=>{ //UserCreateInput is auto generated by prisma so we can use it for typescript.
        return prisma.user.create({data})
    }
}