import prisma from "../config/prisma.js"
// import { Prisma } from "@prisma/client";
import type { CreateUserDTO } from "../dtos/user.dto.js";

export const userRepository={
    createUser:(data:CreateUserDTO)=>{ //UserCreateInput is auto generated by prisma so we can use it for typescript.
        return prisma.user.create({data})
    },

    findByEmail: (email: string) => {
        return prisma.user.findUnique({ where: { email } });
    },
}